### DISCUSSION TITLE
Rust setup and install section of readme files

### DISCUSSION THREAD

**Discussion by sanders41** [thedataquarry/rustinpieces#25] [Ideas]
In the setup section of the readme files for Rust it has people install the dependencies like:

```sh
cargo add csv
cargo add dotenvy
cargo add sqlx
cargo add postgres
cargo add rand
cargo add serde --features derive
cargo add tokio --features full
```

This isn't wrong, but since we already have all the dependencies in the `Cargo.toml` files it also isn't needed. So as a general question, should we remove this from the readme's and discuss how to add dependencies as a broader topic in the book instead?

**Comment by prrao87** [comment]
This is something I haven't found a good answer to in my reading: how do newcomers to Rust know how to update a new Cargo.toml file with the right/latest versions of the crate? Is there a good way to do this other than using `cargo add`?

My problem initially was that for crates like serde and tokio, it's also not obvious how to access the `derive` traits until you specify the right features flag.

For example, how is one supposed to know the `.toml` syntax for specific features as shown below without using `cargo add`?

```toml
serde = { version = "1.0.193", features = ["derive"] }
sqlx = { version = "0.7.3", features = ["runtime-tokio", "postgres"] }
tokio = { version = "1.35.1", features = ["full"] }
```

In Python, we construct the `requirements.txt` file by hand, but it's at least a simple text file and that's how we can get away with just calling `pip install -r requirements.txt`. In Rust, it's hard to explain how the `Cargo.toml` magically constructs itself, which is why I wanted to included this in the docs as well. Or am I missing something basic and there's an easier way? 😅
